-- PR-19: link generated accounting transactions back to recurring_expenses.

ALTER TABLE public.accounting_transactions
  ADD COLUMN IF NOT EXISTS recurring_expense_id uuid REFERENCES public.recurring_expenses(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS generated_for_month text;

ALTER TABLE public.accounting_transactions
  DROP CONSTRAINT IF EXISTS accounting_transactions_generated_for_month_check;

ALTER TABLE public.accounting_transactions
  ADD CONSTRAINT accounting_transactions_generated_for_month_check
  CHECK (
    generated_for_month IS NULL
    OR generated_for_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
  );

CREATE UNIQUE INDEX IF NOT EXISTS uq_at_recurring_month
  ON public.accounting_transactions (recurring_expense_id, generated_for_month)
  WHERE recurring_expense_id IS NOT NULL AND voided_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_at_recurring_month
  ON public.accounting_transactions (org_id, generated_for_month, recurring_expense_id)
  WHERE recurring_expense_id IS NOT NULL;

COMMENT ON COLUMN public.accounting_transactions.recurring_expense_id IS
  'Source recurring_expenses row when this expense was generated automatically.';
COMMENT ON COLUMN public.accounting_transactions.generated_for_month IS
  'YYYY-MM month generated by recurring expense cron; unique with recurring_expense_id while not voided.';
